// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpBfdqCrnKwr9biul3oZwzR4o8xkkELqk',
    appId: '1:293558096946:android:693fb1bc0e90088749182b',
    messagingSenderId: '293558096946',
    projectId: 'laba8-7d2ac',
    databaseURL: 'https://laba8-7d2ac-default-rtdb.firebaseio.com',
    storageBucket: 'laba8-7d2ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADPWennj-14a_TAXwwxBB-_cpMBMlZWKs',
    appId: '1:293558096946:ios:3b1ace9d2bc068fb49182b',
    messagingSenderId: '293558096946',
    projectId: 'laba8-7d2ac',
    databaseURL: 'https://laba8-7d2ac-default-rtdb.firebaseio.com',
    storageBucket: 'laba8-7d2ac.appspot.com',
    iosClientId: '293558096946-13j9akp9in1gqbu8g344a593oar5j4lb.apps.googleusercontent.com',
    iosBundleId: 'com.example.laba8',
  );
}
